spring:
  config:
    import: "classpath:/config/secrets.yaml"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
    username: ${secrets.database.username}
    password: ${secrets.database.password}
  jpa:
    show-sql: true
    generate-ddl: true

logging:
  level:
    uz.mirmaxsudov.chatclonebackend: ${LOG_LEVEL_APP:DEBUG}

server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  endpoint: ${secrets.minio.endpoint}
  access-key: ${secrets.minio.access-key}
  secret-key: ${secrets.minio.secret-key}
  bucket: ${secrets.minio.bucket}
  region: ${secrets.minio.region}

tus:
  stale-chunk-cleanup-enabled: true
  stale-chunk-retention: 1d
  stale-chunk-cleanup-interval: 1h
  stale-chunk-cleanup-initial-delay: 1m

app:
  seed:
    fake-users:
      enabled: false
      password: FakeUser123!
